"""Reproduce Eros's original synthesized cues, music and seamless ambience.

Requires numpy. No external recordings, models, or sampled compositions.
Kenney recordings are kept separately and are never regenerated by this tool.
"""
from pathlib import Path
import argparse
import hashlib
import json
import wave
import numpy as np

ROOT = Path(__file__).resolve().parents[1] / 'assets/audio/original'
RATE = 22050
RNG = np.random.default_rng(87231)


def save(name, samples, loop=False):
    ROOT.mkdir(parents=True, exist_ok=True)
    samples = np.asarray(samples, dtype=float)
    if not loop:
        n = min(len(samples) // 3, int(RATE * .012))
        samples[:n] *= np.linspace(0, 1, n)
        samples[-n:] *= np.linspace(1, 0, n)
    peak = np.max(np.abs(samples))
    samples *= .68 / max(peak, .001)
    with wave.open(str(ROOT / (name + '.wav')), 'wb') as f:
        f.setparams((1, 2, RATE, 0, 'NONE', 'not compressed'))
        f.writeframes((samples * 32767).astype('<i2').tobytes())
    if loop:
        # Godot WAV import options, preserved when the editor reimports the file.
        (ROOT / (name + '.wav.import')).write_text(
            '[remap]\nimporter="wav"\ntype="AudioStreamWAV"\n\n'
            '[deps]\nsource_file="res://assets/audio/original/' + name + '.wav"\n\n'
            '[params]\nforce/8_bit=false\nforce/mono=true\nforce/max_rate=false\n'
            'edit/trim=false\nedit/normalize=false\nedit/loop_mode=2\n'
            'edit/loop_begin=0\nedit/loop_end=-1\ncompress/mode=0\n', encoding='utf-8')


def tone(t, frequency):
    return np.sin(2*np.pi*frequency*t) + .24*np.sin(2*np.pi*2*frequency*t)


def note_frequency(midi):
    return 440 * 2 ** ((midi-69)/12)


def music(name, chords, melody, combat=False):
    duration = 32
    t = np.arange(RATE * duration) / RATE
    out = np.zeros(len(t))
    for i, chord in enumerate(chords):
        start, length = i*8, 8
        local = np.arange(RATE*length)/RATE
        envelope = np.sin(np.pi*local/length)**2
        pad = sum(tone(local, note_frequency(n)) for n in chord)
        out[start*RATE:(start+length)*RATE] += .065*pad*envelope
        # Sparse rounded plucks, with a short simulated echo.
        for j, pitch in enumerate(melody[i]):
            offset = start + j*(1 if combat else 2)
            nt = np.arange(RATE*2)/RATE
            pluck = tone(nt, note_frequency(pitch))*np.exp(-nt*3)*np.minimum(nt/.015,1)
            for delay, gain in [(0,.24),(.24,.06),(.48,.025)]:
                at = int((offset+delay)*RATE)
                count = min(len(pluck),len(out)-at)
                if count>0:out[at:at+count] += pluck[:count]*gain
        if combat:
            for j in range(8):
                nt = np.arange(int(RATE*.35))/RATE
                drum = np.sin(2*np.pi*(55*nt+7*(1-np.exp(-nt*20))))*np.exp(-nt*16)
                at = (start+j)*RATE
                out[at:at+len(drum)] += .2*drum
    save(name,out,True)


def setting_music(name, tavern=False, combat=False):
    """Contrasting folk waltz and minor expedition scores, with wrapped tails."""
    beat = 60 / (96 if tavern else (112 if combat else 84))
    meter = 3 if tavern else 4
    duration = 16 * meter * beat
    out = np.zeros(round(duration * RATE))
    noise_rng = np.random.default_rng(462 if tavern else 871)

    def add(at, pitch, length, gain, instrument):
        t = np.arange(round(length * RATE)) / RATE
        f = note_frequency(pitch)
        if instrument == 'lute':
            # Fast woody attack; upper partials decay before the body resonance.
            sound = sum(np.sin(2*np.pi*f*k*t) * np.exp(-t*(2.6+k*.65)) / k
                        for k in range(1, 9))
            sound *= np.minimum(t/.004, 1)
        elif instrument == 'flute':
            phase = 2*np.pi*f*t + .018*np.sin(2*np.pi*5*t)
            sound = np.sin(phase) + .16*np.sin(2*phase) + .045*np.sin(3*phase)
            sound *= np.minimum(t/.07, 1) * np.minimum((length-t)/.12, 1)
        elif instrument == 'strings':
            sound = sum((np.sin(2*np.pi*f*k*t) + .6*np.sin(2*np.pi*f*k*1.002*t))
                        / k**1.4 for k in range(1, 7))
            sound *= np.minimum(t/.3, 1) * np.minimum((length-t)/.6, 1)
        elif instrument == 'pulse':
            sound = (np.sin(2*np.pi*f*t) + .3*np.sin(2*np.pi*2*f*t))
            sound *= np.exp(-t*5) * np.minimum(t/.02, 1)
        else:
            # Low hand-drum thump and quiet brushed skin texture.
            phase = 2*np.pi*(58*t + 1.8*(1-np.exp(-t*35)))
            sound = np.sin(phase)*np.exp(-t*14)
            noise = noise_rng.normal(0, 1, len(t))
            sound += np.convolve(noise, np.ones(9)/9, mode='same')*.22*np.exp(-t*25)
            sound *= np.minimum(t/.003, 1)
        # Circular accumulation carries reverb/note tails through the loop seam.
        indexes = (round(at*RATE)+np.arange(len(t))) % len(out)
        np.add.at(out, indexes, gain*sound)
        if instrument in ['lute', 'flute']:
            np.add.at(out, (indexes+round(.13*RATE)) % len(out), gain*.1*sound)

    if tavern:
        chords = [[48,52,55], [43,47,50], [45,48,52], [41,45,48]]
        phrases = [[72,76,79,76,74,72], [71,74,79,74,72,71],
                   [72,76,81,79,76,72], [69,72,77,76,74,72]]
        for bar in range(16):
            at = bar*meter*beat
            chord = chords[(bar//2) % 4]
            add(at, chord[0]-12, beat*2, .15, 'lute')
            for pulse in [1,2]:
                for pitch in chord[1:]: add(at+pulse*beat, pitch+12, beat*1.4, .065, 'lute')
            phrase = phrases[(bar//2) % 4]
            for j in range(3):
                pitch = phrase[(bar%2)*3+j]
                add(at+j*beat, pitch, beat*.88, .065, 'flute')
            # A lighter turnaround every four bars keeps the loop from droning.
            if bar%4==3:
                for j,pitch in enumerate([67,69,71,72]):
                    add(at+(1+j*.5)*beat,pitch,beat,.05,'lute')
    else:
        chords = [[45,52,57], [41,48,53], [38,45,50], [40,47,55]]
        for bar in range(16):
            at = bar*meter*beat
            chord = chords[(bar//4) % 4]
            for pitch in chord:
                add(at,pitch,4*beat+.6,.045 if combat else .07,'strings')
            for j in range(8 if combat else 4):
                offset = j*(.5 if combat else 1)*beat
                pitch = chord[0]-12 if j%2==0 else chord[1]-12
                add(at+offset,pitch,beat*.8,.18 if combat else .11,'pulse')
            for j in ([0,1,2,3] if combat else [0,2]):
                add(at+j*beat,36,.4,.16 if combat else .065,'drum')
            if bar%2==1:
                # Sparse lower-register motif leaves room for combat effects.
                for j,pitch in enumerate([chord[2],chord[1]+12,chord[2]+7]):
                    add(at+j*beat,pitch,beat*1.5,.07 if combat else .04,'lute')
    save(name,out,True)


def refresh_manifest():
    path = ROOT.parent / 'sources.json'
    if not path.exists(): return
    manifest = json.loads(path.read_text(encoding='utf-8'))
    for asset in manifest['assets']:
        if asset['file'].startswith('original/'):
            recording = ROOT.parent / asset['file']
            asset['sha256'] = hashlib.sha256(recording.read_bytes()).hexdigest()
    path.write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')


def ambience(name, kind):
    duration=16
    n=RATE*duration
    t=np.arange(n)/RATE
    frequencies=np.fft.rfftfreq(n,1/RATE)
    phase=RNG.uniform(0,2*np.pi,len(frequencies))
    spectrum=np.exp(1j*phase)/np.maximum(frequencies,20)**.75
    spectrum[frequencies>2200]=0
    noise=np.fft.irfft(spectrum,n=n)
    noise/=np.max(np.abs(noise))
    out=noise*(.2+.04*np.sin(2*np.pi*t/duration))
    if kind=='forest':
        for at in [2.1,5.8,10.3,12.4]:
            ct=np.arange(int(.35*RATE))/RATE
            chirp=np.sin(2*np.pi*(1800*ct+600*ct**2))*np.sin(np.pi*ct/.35)**2
            a=int(at*RATE);out[a:a+len(chirp)]+=.14*chirp
    elif kind=='fire':
        for at in RNG.uniform(.5,15,65):
            ct=np.arange(int(.08*RATE))/RATE
            crack=RNG.normal(0,.16,len(ct))*np.exp(-ct*65)
            a=int(at*RATE);out[a:a+len(crack)]+=crack
    elif kind=='water':
        out+=.15*noise*np.sin(2*np.pi*t/.5)**2
    elif kind=='mystic':
        out+=.03*tone(t,110)+.02*tone(t,165)
    else:
        for at in [2.5,6.3,11.7]:
            ct=np.arange(int(.8*RATE))/RATE
            drip=tone(ct,680)*np.exp(-ct*10)*np.minimum(ct/.006,1)
            a=int(at*RATE);out[a:a+len(drip)]+=.17*drip
    # Join ends at a zero crossing while retaining a continuous noise bed.
    fade=np.minimum(np.minimum(t/.08,(duration-t)/.08),1)
    save(name,out*fade,True)


def cues():
    for name,base,end,duration in [
        ('cast_aether',310,740,.48),('cast_fire',150,80,.5),
        ('cast_ice',1100,550,.55),('cast_lightning',900,130,.3),
        ('cast_growth',430,650,.55),('dash',450,110,.28),
        ('heal',440,880,.8),('death',220,55,1.4),
        ('enemy_death',140,45,.45),('combo',330,990,.75),
        ('enemy_attack',100,50,.3),('eruption',90,35,.65),
        ('impact_fire',120,45,.2),('impact_ice',1600,820,.2),
        ('impact_lightning',780,70,.18),('impact_aether',520,260,.22)]:
        t=np.arange(int(duration*RATE))/RATE
        phase=2*np.pi*(base*t+(end-base)*t*t/(2*duration))
        env=np.sin(np.pi*t/duration)**1.5
        noisy=name in ['cast_fire','cast_lightning','dash','enemy_death','enemy_attack','eruption','impact_fire','impact_lightning']
        out=(np.sin(phase)+.25*np.sin(phase*1.5))*env
        if noisy:out=out*.25+RNG.normal(0,.25,len(t))*env
        save(name,out)


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--music-only',action='store_true',help='Rebuild only tavern, dungeon and combat music')
    args=parser.parse_args()
    setting_music('music_tavern',tavern=True)
    setting_music('music_dungeon')
    setting_music('music_combat',combat=True)
    if not args.music_only:
        music('music_menu',[[45,52,57],[41,48,53],[48,55,60],[43,50,55]],[[69,72,76,72],[65,69,72,69],[67,72,76,72],[67,71,74,71]])
        for kind in ['forest','stone','fire','water','mystic']:ambience('ambience_'+kind,kind)
        cues()
    refresh_manifest()
    print('Rebuilt three setting music loops' if args.music_only else 'Created 25 original audio assets')
